
"=======================
" VIM CONFIGURATION FILE
"=======================


"	RUNNING ON THE SYSTEM
runtime! archlinux.vim

" SET AUTOMATIC NUMBERS
set number

" SYNTAX HIGHLIGHT ENABLED
syntax on

" TAB SPACES
set tabstop=2

" CODE AUTO IDENTATION
set autoindent

" VIM COLORSCHEME, LOCATED IN 
" /usr/share/vim/vim82/colors/
colorscheme fanto_vim_theme

